# this is composite workflow that gets the repo ready for actions
# for docs how composite workflows work see https://wallis.dev/blog/composite-github-actions

name: Setup repository
description: Sets this repository up to allow efficient run of various github actions

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: rumblr-${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        pnpm install --frozen-lockfile
          - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: ap-southeast-2

    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Install AWS CDK
      shell: bash
      run: pnpm install aws-cdk

    # - name: Install Playwright
    #   shell: bash
    #   run: |
    #     npx playwright install

    # - name: Setup turborepo cache
    #   uses: dtinth/setup-github-actions-caching-for-turbo@v1
