# name: "Deployment"

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: ./.github/actions/setup
#       - name: Production
#         run: curl -X POST -d {} "${{ secrets.DEPLOY_WEBHOOK_URL}}" -H "Content-Type:application/json"
