# NOT WORKING
# name: "Deployment"

# on:
#   push:
#     branches:
#       - "main"

# permissions:
#   id-token: write
#   contents: read

# env:
#   AWS_REGION: ap-southeast-2

# jobs:
#   backend:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: ./.github/actions/setup
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::${{ secrets.AWS_APP_ID }}:role/action-deploy-Role-QeCRf3Y8ScvQ
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#       - name: cdk synth
#         run: npx --yes cdk synth
#       - name: cdk deploy
#         run: npx --yes cdk deploy --require-approval never
