name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Deploy with CDK
        run: cdk deploy --all --require-approval never
