name: "Deployment"

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_APP_ID }}:role/github-role
          role-session-name: deployment-session
      - name: cdk synth
        run: npx --yes cdk synth
      - name: cdk deploy
        run: npx --yes cdk deploy --require-approval never
