name: Deployment

on:
  push:
    branches:
      - main

jobs:
  production:
    # opens the possibility of multiple environments depending on the branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install AWS CLI
        shell: bash
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Install AWS CDK
        shell: bash
        run: npm install -g aws-cdk

      - name: Build
        run: pnpm build

      - name: Deploy GraphQL API
        run: pnpm -F backend deploy:ci

      - name: Deploy Vue App
        run: pnpm -F vue-project deploy:ci
