name: deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: "production"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-southeast-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACC_ID }}:role/action-deploy-Role-QeCRf3Y8ScvQ
          role-session-name: deployment-session
      - name: cdk synth
        run: npx --yes cdk synth
      - name: cdk deploy
        run: npx --yes cdk deploy --require-approval never
